# Generated by Django 5.2.1 on 2025-06-04 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_customuser_is_staff_customuser_is_superuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_superuser',
        ),
    ]
