# Generated by Django 5.2.1 on 2025-06-04 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
