# Generated by Django 5.2.1 on 2025-06-05 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_alter_userprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='phone',
        ),
    ]
