# Generated by Django 5.2.1 on 2025-06-06 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_recipe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
