# Generated by Django 5.2.1 on 2025-06-10 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
