# Generated by Django 5.2.1 on 2025-06-11 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0030_customuser_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='last_login',
        ),
    ]
