# Generated by Django 5.2.1 on 2025-06-11 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0032_passwordresettoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PasswordResetToken',
        ),
    ]
